# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ee019444c3aa426abacefd093db469e81c57e97efb33a6288fcc7cb8187063fe0bb4c9aee70532fc9d87bd89f64584e28607ebd45c35f6d98e384e45744036d

test:
  secret_key_base: ad6f8cfb328c28142c01296f2349917d14469558b0386c470d2f2710f09702f1cd19105a7aa223a2801985e9189fe7209ed41030ecd8b69925717f659ccb4c94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
